{% set name = "optimask" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/optimask-{{ version }}.tar.gz
  sha256: 705852c749651f0d8b3904d99772ef81d8a8613e29c734ec91899b27a4cfea94

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - numpy
    - pandas
    - numba

test:
  imports:
    - optimask
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CyrilJl/optimask
  dev_url: https://github.com/CyrilJl/optimask
  doc_url: https://optimask.readthedocs.io/en/latest/index.html
  summary: 'OptiMask: extracting the largest (non-contiguous) submatrix without NaN'
  description: 'OptiMask: extracting the largest (non-contiguous) submatrix without NaN'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
