{% set name = "optimask" %}
{% set version = "1.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/optimask-{{ version }}.tar.gz
  sha256: 8563814fb37791086cba02932c19a82d671d036719d518a353e40a0b95329edf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - numba

test:
  imports:
    - optimask
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CyrilJl/optimask
  dev_url: https://github.com/CyrilJl/optimask
  doc_url: https://optimask.readthedocs.io/en/latest/index.html
  summary: 'OptiMask: extracting the largest (non-contiguous) submatrix without NaN'
  description: 'OptiMask: extracting the largest (non-contiguous) submatrix without NaN'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
