{% set name = "optimask" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optimask-{{ version }}.tar.gz
  sha256: 03a44dc098ad12ae88766bb57ed0cb4b653e97c22a088eb7c0160af01730cfa7

build:
  script:
    - {{ PYTHON }} setup.py build_ext
    - {{ PYTHON }} -m pip install . -vv
  number: 5

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
    - numpy                                # [build_platform != target_platform]
    - setuptools
  host:
    - python
    - pip
    - cython
    - numpy
    - pandas
  run:
    - python
    - numpy
    - pandas

test:
  imports:
    - optimask
  commands:
    - pip check
  requires:
    - pip
    - numpy
    - pandas

about:
  home: https://github.com/CyrilJl/optimask
  summary: 'OptiMask: extracting the largest (non-contiguous) submatrix without NaN'
  description: 'OptiMask: extracting the largest (non-contiguous) submatrix without NaN'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
