{% set name = "optimask" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optimask-{{ version }}.tar.gz
  sha256: 606f82813cfad0f063f25641c50c4c6ad8102d1f3ffe99a10840a36022c67d70

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - numpy
    - pandas
    - numba

test:
  imports:
    - optimask
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CyrilJl/optimask
  dev_url: https://github.com/CyrilJl/optimask
  doc_url: https://optimask.readthedocs.io/en/latest/index.html
  summary: 'OptiMask: extracting the largest (non-contiguous) submatrix without NaN'
  description: 'OptiMask: extracting the largest (non-contiguous) submatrix without NaN'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
