{% set name = "optimask" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optimask-{{ version }}.tar.gz
  sha256: dd91550b11b531d2295cb50b57c7e8eaeed8ebc6531a2f9a8ee3497a1c69b286

build:
  script:
    - cython optimask/optimask_cython.pyx
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - python
    - cython
    - numpy
    - setuptools
  host:
    - python
    - pip
    - cython
    - numpy
    - pandas
  run:
    - python
    - numpy
    - pandas

test:
  imports:
    - optimask
  commands:
    - pip check
  requires:
    - pip
    - numpy
    - pandas

about:
  home: https://github.com/CyrilJl/optimask
  dev_url: https://github.com/CyrilJl/optimask
  doc_url: https://optimask.readthedocs.io/en/latest/index.html
  summary: 'OptiMask: extracting the largest (non-contiguous) submatrix without NaN'
  description: 'OptiMask: extracting the largest (non-contiguous) submatrix without NaN'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
