{% set name = "optimask" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/optimask-{{ version }}.tar.gz
  sha256: 6c67cfcd0bc2c7fb4a3772744e504935764bd28954d2cd36db14df92fe5a70a7

build:
  script:
    - {{ PYTHON }} setup.py build_ext
    - {{ PYTHON }} -m pip install . -vv
  number: 4

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - python
    - cython
    - numpy
    - setuptools
  host:
    - python
    - pip
    - cython
    - numpy
    - pandas
  run:
    - python
    - {{ pin_compatible("numpy") }}
    - numpy
    - pandas

test:
  imports:
    - optimask
  commands:
    - pip check
  requires:
    - pip
    - numpy
    - pandas

about:
  home: https://github.com/CyrilJl/optimask
  summary: 'OptiMask: extracting the largest (non-contiguous) submatrix without NaN'
  description: 'OptiMask: extracting the largest (non-contiguous) submatrix without NaN'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - CyrilJl
